/* tslint:disable */
/* eslint-disable */
/**
 * agentctl API
 * Schema-first contract for `agentctl`.  The Go CLI is the current implementation, but this API document is the canonical cross-language contract for generated JS and Python clients. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Decision,
  GateRequest,
} from '../models/index';
import {
    DecisionFromJSON,
    DecisionToJSON,
    GateRequestFromJSON,
    GateRequestToJSON,
} from '../models/index';

export interface GateActionRequest {
    gateRequest: GateRequest;
}

/**
 * 
 */
export class GateApi extends runtime.BaseAPI {

    /**
     * Evaluate a risky action against policy
     */
    async gateActionRaw(requestParameters: GateActionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Decision>> {
        if (requestParameters['gateRequest'] == null) {
            throw new runtime.RequiredError(
                'gateRequest',
                'Required parameter "gateRequest" was null or undefined when calling gateAction().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/v1/gate`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GateRequestToJSON(requestParameters['gateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DecisionFromJSON(jsonValue));
    }

    /**
     * Evaluate a risky action against policy
     */
    async gateAction(requestParameters: GateActionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Decision> {
        const response = await this.gateActionRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
