/* tslint:disable */
/* eslint-disable */
/**
 * agentctl API
 * Schema-first contract for `agentctl`.  The Go CLI is the current implementation, but this API document is the canonical cross-language contract for generated JS and Python clients. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ReplayRequest,
  ReplayResponse,
} from '../models/index';
import {
    ReplayRequestFromJSON,
    ReplayRequestToJSON,
    ReplayResponseFromJSON,
    ReplayResponseToJSON,
} from '../models/index';

export interface ReplaySessionRequest {
    replayRequest: ReplayRequest;
}

/**
 * 
 */
export class ReplayApi extends runtime.BaseAPI {

    /**
     * Re-evaluate a recorded session with a given policy
     */
    async replaySessionRaw(requestParameters: ReplaySessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ReplayResponse>> {
        if (requestParameters['replayRequest'] == null) {
            throw new runtime.RequiredError(
                'replayRequest',
                'Required parameter "replayRequest" was null or undefined when calling replaySession().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/v1/replay`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ReplayRequestToJSON(requestParameters['replayRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReplayResponseFromJSON(jsonValue));
    }

    /**
     * Re-evaluate a recorded session with a given policy
     */
    async replaySession(requestParameters: ReplaySessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ReplayResponse> {
        const response = await this.replaySessionRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
