/* tslint:disable */
/* eslint-disable */
/**
 * agentctl API
 * Schema-first contract for `agentctl`.  The Go CLI is the current implementation, but this API document is the canonical cross-language contract for generated JS and Python clients. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Action,
  TraceListResponse,
  Verdict,
} from '../models/index';
import {
    ActionFromJSON,
    ActionToJSON,
    TraceListResponseFromJSON,
    TraceListResponseToJSON,
    VerdictFromJSON,
    VerdictToJSON,
} from '../models/index';

export interface ListTracesRequest {
    sessionId?: string;
    action?: Action;
    verdict?: Verdict;
    _package?: string;
    since?: Date;
    until?: Date;
    limit?: number;
}

/**
 * 
 */
export class TraceApi extends runtime.BaseAPI {

    /**
     * List or search traces
     */
    async listTracesRaw(requestParameters: ListTracesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TraceListResponse>> {
        const queryParameters: any = {};

        if (requestParameters['sessionId'] != null) {
            queryParameters['session_id'] = requestParameters['sessionId'];
        }

        if (requestParameters['action'] != null) {
            queryParameters['action'] = requestParameters['action'];
        }

        if (requestParameters['verdict'] != null) {
            queryParameters['verdict'] = requestParameters['verdict'];
        }

        if (requestParameters['_package'] != null) {
            queryParameters['package'] = requestParameters['_package'];
        }

        if (requestParameters['since'] != null) {
            queryParameters['since'] = (requestParameters['since'] as any).toISOString();
        }

        if (requestParameters['until'] != null) {
            queryParameters['until'] = (requestParameters['until'] as any).toISOString();
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/traces`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TraceListResponseFromJSON(jsonValue));
    }

    /**
     * List or search traces
     */
    async listTraces(requestParameters: ListTracesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TraceListResponse> {
        const response = await this.listTracesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
