# coding: utf-8

"""
    agentctl API

    Schema-first contract for `agentctl`.  The Go CLI is the current implementation, but this API document is the canonical cross-language contract for generated JS and Python clients. 

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class Action(str, Enum):
    """
    Action
    """

    """
    allowed enum values
    """
    INSTALL_PACKAGE = 'install_package'
    RUN_CODE = 'run_code'
    ACCESS_SECRET = 'access_secret'
    WRITE_FILE = 'write_file'
    CALL_EXTERNAL_API = 'call_external_api'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of Action from a JSON string"""
        return cls(json.loads(json_str))


