# coding: utf-8

"""
    agentctl API

    Schema-first contract for `agentctl`.  The Go CLI is the current implementation, but this API document is the canonical cross-language contract for generated JS and Python clients. 

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from agentctl_sdk.models.access_secret_params import AccessSecretParams
from agentctl_sdk.models.call_external_api_params import CallExternalAPIParams
from agentctl_sdk.models.install_package_params import InstallPackageParams
from agentctl_sdk.models.run_code_params import RunCodeParams
from agentctl_sdk.models.write_file_params import WriteFileParams
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

ACTIONPARAMS_ONE_OF_SCHEMAS = ["AccessSecretParams", "CallExternalAPIParams", "InstallPackageParams", "RunCodeParams", "WriteFileParams"]

class ActionParams(BaseModel):
    """
    ActionParams
    """
    # data type: InstallPackageParams
    oneof_schema_1_validator: Optional[InstallPackageParams] = None
    # data type: RunCodeParams
    oneof_schema_2_validator: Optional[RunCodeParams] = None
    # data type: AccessSecretParams
    oneof_schema_3_validator: Optional[AccessSecretParams] = None
    # data type: WriteFileParams
    oneof_schema_4_validator: Optional[WriteFileParams] = None
    # data type: CallExternalAPIParams
    oneof_schema_5_validator: Optional[CallExternalAPIParams] = None
    actual_instance: Optional[Union[AccessSecretParams, CallExternalAPIParams, InstallPackageParams, RunCodeParams, WriteFileParams]] = None
    one_of_schemas: Set[str] = { "AccessSecretParams", "CallExternalAPIParams", "InstallPackageParams", "RunCodeParams", "WriteFileParams" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = ActionParams.model_construct()
        error_messages = []
        match = 0
        # validate data type: InstallPackageParams
        if not isinstance(v, InstallPackageParams):
            error_messages.append(f"Error! Input type `{type(v)}` is not `InstallPackageParams`")
        else:
            match += 1
        # validate data type: RunCodeParams
        if not isinstance(v, RunCodeParams):
            error_messages.append(f"Error! Input type `{type(v)}` is not `RunCodeParams`")
        else:
            match += 1
        # validate data type: AccessSecretParams
        if not isinstance(v, AccessSecretParams):
            error_messages.append(f"Error! Input type `{type(v)}` is not `AccessSecretParams`")
        else:
            match += 1
        # validate data type: WriteFileParams
        if not isinstance(v, WriteFileParams):
            error_messages.append(f"Error! Input type `{type(v)}` is not `WriteFileParams`")
        else:
            match += 1
        # validate data type: CallExternalAPIParams
        if not isinstance(v, CallExternalAPIParams):
            error_messages.append(f"Error! Input type `{type(v)}` is not `CallExternalAPIParams`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in ActionParams with oneOf schemas: AccessSecretParams, CallExternalAPIParams, InstallPackageParams, RunCodeParams, WriteFileParams. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in ActionParams with oneOf schemas: AccessSecretParams, CallExternalAPIParams, InstallPackageParams, RunCodeParams, WriteFileParams. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into InstallPackageParams
        try:
            instance.actual_instance = InstallPackageParams.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into RunCodeParams
        try:
            instance.actual_instance = RunCodeParams.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into AccessSecretParams
        try:
            instance.actual_instance = AccessSecretParams.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into WriteFileParams
        try:
            instance.actual_instance = WriteFileParams.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into CallExternalAPIParams
        try:
            instance.actual_instance = CallExternalAPIParams.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into ActionParams with oneOf schemas: AccessSecretParams, CallExternalAPIParams, InstallPackageParams, RunCodeParams, WriteFileParams. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into ActionParams with oneOf schemas: AccessSecretParams, CallExternalAPIParams, InstallPackageParams, RunCodeParams, WriteFileParams. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], AccessSecretParams, CallExternalAPIParams, InstallPackageParams, RunCodeParams, WriteFileParams]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


