# coding: utf-8

"""
    agentctl API

    Schema-first contract for `agentctl`.  The Go CLI is the current implementation, but this API document is the canonical cross-language contract for generated JS and Python clients. 

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from agentctl_sdk.models.action_request import ActionRequest
from agentctl_sdk.models.verdict import Verdict
from typing import Optional, Set
from typing_extensions import Self

class Decision(BaseModel):
    """
    Decision
    """ # noqa: E501
    trace_id: StrictStr
    verdict: Verdict
    risk_score: Annotated[int, Field(le=100, strict=True, ge=0)]
    timestamp: datetime
    request: ActionRequest
    reason: StrictStr
    matched_rules: Optional[List[StrictStr]] = None
    approval_required: Optional[StrictBool] = None
    approved_by: Optional[StrictStr] = None
    eval_duration_ms: Union[StrictFloat, StrictInt]
    __properties: ClassVar[List[str]] = ["trace_id", "verdict", "risk_score", "timestamp", "request", "reason", "matched_rules", "approval_required", "approved_by", "eval_duration_ms"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Decision from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of request
        if self.request:
            _dict['request'] = self.request.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Decision from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "trace_id": obj.get("trace_id"),
            "verdict": obj.get("verdict"),
            "risk_score": obj.get("risk_score"),
            "timestamp": obj.get("timestamp"),
            "request": ActionRequest.from_dict(obj["request"]) if obj.get("request") is not None else None,
            "reason": obj.get("reason"),
            "matched_rules": obj.get("matched_rules"),
            "approval_required": obj.get("approval_required"),
            "approved_by": obj.get("approved_by"),
            "eval_duration_ms": obj.get("eval_duration_ms")
        })
        return _obj


