# coding: utf-8

"""
    agentctl API

    Schema-first contract for `agentctl`.  The Go CLI is the current implementation, but this API document is the canonical cross-language contract for generated JS and Python clients. 

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from agentctl_sdk.api.gate_api import GateApi


class TestGateApi(unittest.TestCase):
    """GateApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GateApi()

    def tearDown(self) -> None:
        pass

    def test_gate_action(self) -> None:
        """Test case for gate_action

        Evaluate a risky action against policy
        """
        pass


if __name__ == '__main__':
    unittest.main()
