# coding: utf-8

"""
    agentctl API

    Schema-first contract for `agentctl`.  The Go CLI is the current implementation, but this API document is the canonical cross-language contract for generated JS and Python clients. 

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from agentctl_sdk.api.trace_api import TraceApi


class TestTraceApi(unittest.TestCase):
    """TraceApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TraceApi()

    def tearDown(self) -> None:
        pass

    def test_list_traces(self) -> None:
        """Test case for list_traces

        List or search traces
        """
        pass


if __name__ == '__main__':
    unittest.main()
