# coding: utf-8

"""
    agentctl API

    Schema-first contract for `agentctl`.  The Go CLI is the current implementation, but this API document is the canonical cross-language contract for generated JS and Python clients. 

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from agentctl_sdk.models.action_params import ActionParams

class TestActionParams(unittest.TestCase):
    """ActionParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ActionParams:
        """Test ActionParams
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ActionParams`
        """
        model = ActionParams()
        if include_optional:
            return ActionParams(
                manager = '',
                package = '',
                version = '',
                hash = '',
                pinned = True,
                language = '',
                command = '',
                stdin = '',
                network = True,
                name = '',
                scope = '',
                ttl = 56,
                path = '',
                operation = '',
                size_bytes = 56,
                url = '',
                method = '',
                domain = ''
            )
        else:
            return ActionParams(
                manager = '',
                package = '',
                language = '',
                command = '',
                name = '',
                path = '',
                operation = '',
                url = '',
                method = '',
        )
        """

    def testActionParams(self):
        """Test ActionParams"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
