# coding: utf-8

"""
    agentctl API

    Schema-first contract for `agentctl`.  The Go CLI is the current implementation, but this API document is the canonical cross-language contract for generated JS and Python clients. 

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from agentctl_sdk.models.access_secret_params import AccessSecretParams

class TestAccessSecretParams(unittest.TestCase):
    """AccessSecretParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AccessSecretParams:
        """Test AccessSecretParams
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AccessSecretParams`
        """
        model = AccessSecretParams()
        if include_optional:
            return AccessSecretParams(
                name = '',
                scope = '',
                ttl = 56
            )
        else:
            return AccessSecretParams(
                name = '',
        )
        """

    def testAccessSecretParams(self):
        """Test AccessSecretParams"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
