# coding: utf-8

"""
    agentctl API

    Schema-first contract for `agentctl`.  The Go CLI is the current implementation, but this API document is the canonical cross-language contract for generated JS and Python clients. 

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from agentctl_sdk.models.gate_request import GateRequest

class TestGateRequest(unittest.TestCase):
    """GateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GateRequest:
        """Test GateRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GateRequest`
        """
        model = GateRequest()
        if include_optional:
            return GateRequest(
                action = 'install_package',
                params = None,
                reason = '',
                context = agentctl_sdk.models.request_context.RequestContext(
                    session_id = '', 
                    model = '', 
                    agent = '', 
                    turn = 56, 
                    timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
            )
        else:
            return GateRequest(
                action = 'install_package',
                params = None,
                reason = '',
        )
        """

    def testGateRequest(self):
        """Test GateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
