# coding: utf-8

"""
    agentctl API

    Schema-first contract for `agentctl`.  The Go CLI is the current implementation, but this API document is the canonical cross-language contract for generated JS and Python clients. 

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from agentctl_sdk.models.trace_list_response import TraceListResponse

class TestTraceListResponse(unittest.TestCase):
    """TraceListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TraceListResponse:
        """Test TraceListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TraceListResponse`
        """
        model = TraceListResponse()
        if include_optional:
            return TraceListResponse(
                traces = [
                    agentctl_sdk.models.decision.Decision(
                        trace_id = '', 
                        verdict = 'allow', 
                        risk_score = 0, 
                        timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        request = null, 
                        reason = '', 
                        matched_rules = [
                            ''
                            ], 
                        approval_required = True, 
                        approved_by = '', 
                        eval_duration_ms = 1.337, )
                    ]
            )
        else:
            return TraceListResponse(
                traces = [
                    agentctl_sdk.models.decision.Decision(
                        trace_id = '', 
                        verdict = 'allow', 
                        risk_score = 0, 
                        timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        request = null, 
                        reason = '', 
                        matched_rules = [
                            ''
                            ], 
                        approval_required = True, 
                        approved_by = '', 
                        eval_duration_ms = 1.337, )
                    ],
        )
        """

    def testTraceListResponse(self):
        """Test TraceListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
