# coding: utf-8

"""
    agentctl API

    Schema-first contract for `agentctl`.  The Go CLI is the current implementation, but this API document is the canonical cross-language contract for generated JS and Python clients. 

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from agentctl_sdk.models.verdict import Verdict

class TestVerdict(unittest.TestCase):
    """Verdict unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVerdict(self):
        """Test Verdict"""
        # inst = Verdict()

if __name__ == '__main__':
    unittest.main()
