# coding: utf-8

"""
    agentctl API

    Schema-first contract for `agentctl`.  The Go CLI is the current implementation, but this API document is the canonical cross-language contract for generated JS and Python clients. 

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from agentctl_sdk.models.replay_request import ReplayRequest

class TestReplayRequest(unittest.TestCase):
    """ReplayRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReplayRequest:
        """Test ReplayRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReplayRequest`
        """
        model = ReplayRequest()
        if include_optional:
            return ReplayRequest(
                session_id = '',
                policy_path = '',
                limit = 1
            )
        else:
            return ReplayRequest(
                session_id = '',
        )
        """

    def testReplayRequest(self):
        """Test ReplayRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
