# coding: utf-8

"""
    agentctl API

    Schema-first contract for `agentctl`.  The Go CLI is the current implementation, but this API document is the canonical cross-language contract for generated JS and Python clients. 

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from agentctl_sdk.models.call_external_api_params import CallExternalAPIParams

class TestCallExternalAPIParams(unittest.TestCase):
    """CallExternalAPIParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CallExternalAPIParams:
        """Test CallExternalAPIParams
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CallExternalAPIParams`
        """
        model = CallExternalAPIParams()
        if include_optional:
            return CallExternalAPIParams(
                url = '',
                method = '',
                domain = ''
            )
        else:
            return CallExternalAPIParams(
                url = '',
                method = '',
        )
        """

    def testCallExternalAPIParams(self):
        """Test CallExternalAPIParams"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
