# coding: utf-8

"""
    agentctl API

    Schema-first contract for `agentctl`.  The Go CLI is the current implementation, but this API document is the canonical cross-language contract for generated JS and Python clients. 

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from agentctl_sdk.api.replay_api import ReplayApi


class TestReplayApi(unittest.TestCase):
    """ReplayApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ReplayApi()

    def tearDown(self) -> None:
        pass

    def test_replay_session(self) -> None:
        """Test case for replay_session

        Re-evaluate a recorded session with a given policy
        """
        pass


if __name__ == '__main__':
    unittest.main()
