/* tslint:disable */
/* eslint-disable */
/**
 * agentctl API
 * Schema-first contract for `agentctl`.  The Go CLI is the current implementation, but this API document is the canonical cross-language contract for generated JS and Python clients. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccessSecretParams
 */
export interface AccessSecretParams {
    /**
     * 
     * @type {string}
     * @memberof AccessSecretParams
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof AccessSecretParams
     */
    scope?: string;
    /**
     * 
     * @type {number}
     * @memberof AccessSecretParams
     */
    ttl?: number;
}

/**
 * Check if a given object implements the AccessSecretParams interface.
 */
export function instanceOfAccessSecretParams(value: object): value is AccessSecretParams {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function AccessSecretParamsFromJSON(json: any): AccessSecretParams {
    return AccessSecretParamsFromJSONTyped(json, false);
}

export function AccessSecretParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccessSecretParams {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'scope': json['scope'] == null ? undefined : json['scope'],
        'ttl': json['ttl'] == null ? undefined : json['ttl'],
    };
}

export function AccessSecretParamsToJSON(value?: AccessSecretParams | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'scope': value['scope'],
        'ttl': value['ttl'],
    };
}

