/* tslint:disable */
/* eslint-disable */
/**
 * agentctl API
 * Schema-first contract for `agentctl`.  The Go CLI is the current implementation, but this API document is the canonical cross-language contract for generated JS and Python clients. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const Action = {
    InstallPackage: 'install_package',
    RunCode: 'run_code',
    AccessSecret: 'access_secret',
    WriteFile: 'write_file',
    CallExternalApi: 'call_external_api'
} as const;
export type Action = typeof Action[keyof typeof Action];


export function instanceOfAction(value: any): boolean {
    for (const key in Action) {
        if (Object.prototype.hasOwnProperty.call(Action, key)) {
            if (Action[key as keyof typeof Action] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ActionFromJSON(json: any): Action {
    return ActionFromJSONTyped(json, false);
}

export function ActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Action {
    return json as Action;
}

export function ActionToJSON(value?: Action | null): any {
    return value as any;
}

