/* tslint:disable */
/* eslint-disable */
/**
 * agentctl API
 * Schema-first contract for `agentctl`.  The Go CLI is the current implementation, but this API document is the canonical cross-language contract for generated JS and Python clients. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { AccessSecretParams } from './AccessSecretParams';
import {
    instanceOfAccessSecretParams,
    AccessSecretParamsFromJSON,
    AccessSecretParamsFromJSONTyped,
    AccessSecretParamsToJSON,
} from './AccessSecretParams';
import type { CallExternalAPIParams } from './CallExternalAPIParams';
import {
    instanceOfCallExternalAPIParams,
    CallExternalAPIParamsFromJSON,
    CallExternalAPIParamsFromJSONTyped,
    CallExternalAPIParamsToJSON,
} from './CallExternalAPIParams';
import type { InstallPackageParams } from './InstallPackageParams';
import {
    instanceOfInstallPackageParams,
    InstallPackageParamsFromJSON,
    InstallPackageParamsFromJSONTyped,
    InstallPackageParamsToJSON,
} from './InstallPackageParams';
import type { RunCodeParams } from './RunCodeParams';
import {
    instanceOfRunCodeParams,
    RunCodeParamsFromJSON,
    RunCodeParamsFromJSONTyped,
    RunCodeParamsToJSON,
} from './RunCodeParams';
import type { WriteFileParams } from './WriteFileParams';
import {
    instanceOfWriteFileParams,
    WriteFileParamsFromJSON,
    WriteFileParamsFromJSONTyped,
    WriteFileParamsToJSON,
} from './WriteFileParams';

/**
 * @type ActionParams
 * 
 * @export
 */
export type ActionParams = AccessSecretParams | CallExternalAPIParams | InstallPackageParams | RunCodeParams | WriteFileParams;

export function ActionParamsFromJSON(json: any): ActionParams {
    return ActionParamsFromJSONTyped(json, false);
}

export function ActionParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActionParams {
    if (json == null) {
        return json;
    }
    if (instanceOfAccessSecretParams(json)) {
        return AccessSecretParamsFromJSONTyped(json, true);
    }
    if (instanceOfCallExternalAPIParams(json)) {
        return CallExternalAPIParamsFromJSONTyped(json, true);
    }
    if (instanceOfInstallPackageParams(json)) {
        return InstallPackageParamsFromJSONTyped(json, true);
    }
    if (instanceOfRunCodeParams(json)) {
        return RunCodeParamsFromJSONTyped(json, true);
    }
    if (instanceOfWriteFileParams(json)) {
        return WriteFileParamsFromJSONTyped(json, true);
    }

    return {} as any;
}

export function ActionParamsToJSON(value?: ActionParams | null): any {
    if (value == null) {
        return value;
    }

    if (instanceOfAccessSecretParams(value)) {
        return AccessSecretParamsToJSON(value as AccessSecretParams);
    }
    if (instanceOfCallExternalAPIParams(value)) {
        return CallExternalAPIParamsToJSON(value as CallExternalAPIParams);
    }
    if (instanceOfInstallPackageParams(value)) {
        return InstallPackageParamsToJSON(value as InstallPackageParams);
    }
    if (instanceOfRunCodeParams(value)) {
        return RunCodeParamsToJSON(value as RunCodeParams);
    }
    if (instanceOfWriteFileParams(value)) {
        return WriteFileParamsToJSON(value as WriteFileParams);
    }

    return {};
}

