/* tslint:disable */
/* eslint-disable */
/**
 * agentctl API
 * Schema-first contract for `agentctl`.  The Go CLI is the current implementation, but this API document is the canonical cross-language contract for generated JS and Python clients. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CallExternalAPIParams
 */
export interface CallExternalAPIParams {
    /**
     * 
     * @type {string}
     * @memberof CallExternalAPIParams
     */
    url: string;
    /**
     * 
     * @type {string}
     * @memberof CallExternalAPIParams
     */
    method: string;
    /**
     * 
     * @type {string}
     * @memberof CallExternalAPIParams
     */
    domain?: string;
}

/**
 * Check if a given object implements the CallExternalAPIParams interface.
 */
export function instanceOfCallExternalAPIParams(value: object): value is CallExternalAPIParams {
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('method' in value) || value['method'] === undefined) return false;
    return true;
}

export function CallExternalAPIParamsFromJSON(json: any): CallExternalAPIParams {
    return CallExternalAPIParamsFromJSONTyped(json, false);
}

export function CallExternalAPIParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CallExternalAPIParams {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
        'method': json['method'],
        'domain': json['domain'] == null ? undefined : json['domain'],
    };
}

export function CallExternalAPIParamsToJSON(value?: CallExternalAPIParams | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'url': value['url'],
        'method': value['method'],
        'domain': value['domain'],
    };
}

