/* tslint:disable */
/* eslint-disable */
/**
 * agentctl API
 * Schema-first contract for `agentctl`.  The Go CLI is the current implementation, but this API document is the canonical cross-language contract for generated JS and Python clients. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ActionRequest } from './ActionRequest';
import {
    ActionRequestFromJSON,
    ActionRequestFromJSONTyped,
    ActionRequestToJSON,
} from './ActionRequest';
import type { Verdict } from './Verdict';
import {
    VerdictFromJSON,
    VerdictFromJSONTyped,
    VerdictToJSON,
} from './Verdict';

/**
 * 
 * @export
 * @interface Decision
 */
export interface Decision {
    /**
     * 
     * @type {string}
     * @memberof Decision
     */
    traceId: string;
    /**
     * 
     * @type {Verdict}
     * @memberof Decision
     */
    verdict: Verdict;
    /**
     * 
     * @type {number}
     * @memberof Decision
     */
    riskScore: number;
    /**
     * 
     * @type {Date}
     * @memberof Decision
     */
    timestamp: Date;
    /**
     * 
     * @type {ActionRequest}
     * @memberof Decision
     */
    request: ActionRequest;
    /**
     * 
     * @type {string}
     * @memberof Decision
     */
    reason: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof Decision
     */
    matchedRules?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof Decision
     */
    approvalRequired?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Decision
     */
    approvedBy?: string;
    /**
     * 
     * @type {number}
     * @memberof Decision
     */
    evalDurationMs: number;
}



/**
 * Check if a given object implements the Decision interface.
 */
export function instanceOfDecision(value: object): value is Decision {
    if (!('traceId' in value) || value['traceId'] === undefined) return false;
    if (!('verdict' in value) || value['verdict'] === undefined) return false;
    if (!('riskScore' in value) || value['riskScore'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    if (!('request' in value) || value['request'] === undefined) return false;
    if (!('reason' in value) || value['reason'] === undefined) return false;
    if (!('evalDurationMs' in value) || value['evalDurationMs'] === undefined) return false;
    return true;
}

export function DecisionFromJSON(json: any): Decision {
    return DecisionFromJSONTyped(json, false);
}

export function DecisionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Decision {
    if (json == null) {
        return json;
    }
    return {
        
        'traceId': json['trace_id'],
        'verdict': VerdictFromJSON(json['verdict']),
        'riskScore': json['risk_score'],
        'timestamp': (new Date(json['timestamp'])),
        'request': ActionRequestFromJSON(json['request']),
        'reason': json['reason'],
        'matchedRules': json['matched_rules'] == null ? undefined : json['matched_rules'],
        'approvalRequired': json['approval_required'] == null ? undefined : json['approval_required'],
        'approvedBy': json['approved_by'] == null ? undefined : json['approved_by'],
        'evalDurationMs': json['eval_duration_ms'],
    };
}

export function DecisionToJSON(value?: Decision | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'trace_id': value['traceId'],
        'verdict': VerdictToJSON(value['verdict']),
        'risk_score': value['riskScore'],
        'timestamp': ((value['timestamp']).toISOString()),
        'request': ActionRequestToJSON(value['request']),
        'reason': value['reason'],
        'matched_rules': value['matchedRules'],
        'approval_required': value['approvalRequired'],
        'approved_by': value['approvedBy'],
        'eval_duration_ms': value['evalDurationMs'],
    };
}

