/* tslint:disable */
/* eslint-disable */
/**
 * agentctl API
 * Schema-first contract for `agentctl`.  The Go CLI is the current implementation, but this API document is the canonical cross-language contract for generated JS and Python clients. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Action } from './Action';
import {
    ActionFromJSON,
    ActionFromJSONTyped,
    ActionToJSON,
} from './Action';
import type { ActionParams } from './ActionParams';
import {
    ActionParamsFromJSON,
    ActionParamsFromJSONTyped,
    ActionParamsToJSON,
} from './ActionParams';
import type { ModelRequestContext } from './ModelRequestContext';
import {
    ModelRequestContextFromJSON,
    ModelRequestContextFromJSONTyped,
    ModelRequestContextToJSON,
} from './ModelRequestContext';

/**
 * 
 * @export
 * @interface GateRequest
 */
export interface GateRequest {
    /**
     * 
     * @type {Action}
     * @memberof GateRequest
     */
    action: Action;
    /**
     * 
     * @type {ActionParams}
     * @memberof GateRequest
     */
    params: ActionParams;
    /**
     * 
     * @type {string}
     * @memberof GateRequest
     */
    reason: string;
    /**
     * 
     * @type {ModelRequestContext}
     * @memberof GateRequest
     */
    context?: ModelRequestContext;
}



/**
 * Check if a given object implements the GateRequest interface.
 */
export function instanceOfGateRequest(value: object): value is GateRequest {
    if (!('action' in value) || value['action'] === undefined) return false;
    if (!('params' in value) || value['params'] === undefined) return false;
    if (!('reason' in value) || value['reason'] === undefined) return false;
    return true;
}

export function GateRequestFromJSON(json: any): GateRequest {
    return GateRequestFromJSONTyped(json, false);
}

export function GateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'action': ActionFromJSON(json['action']),
        'params': ActionParamsFromJSON(json['params']),
        'reason': json['reason'],
        'context': json['context'] == null ? undefined : ModelRequestContextFromJSON(json['context']),
    };
}

export function GateRequestToJSON(value?: GateRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'action': ActionToJSON(value['action']),
        'params': ActionParamsToJSON(value['params']),
        'reason': value['reason'],
        'context': ModelRequestContextToJSON(value['context']),
    };
}

