/* tslint:disable */
/* eslint-disable */
/**
 * agentctl API
 * Schema-first contract for `agentctl`.  The Go CLI is the current implementation, but this API document is the canonical cross-language contract for generated JS and Python clients. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InstallPackageParams
 */
export interface InstallPackageParams {
    /**
     * 
     * @type {string}
     * @memberof InstallPackageParams
     */
    manager: string;
    /**
     * 
     * @type {string}
     * @memberof InstallPackageParams
     */
    _package: string;
    /**
     * 
     * @type {string}
     * @memberof InstallPackageParams
     */
    version?: string;
    /**
     * 
     * @type {string}
     * @memberof InstallPackageParams
     */
    hash?: string;
    /**
     * 
     * @type {boolean}
     * @memberof InstallPackageParams
     */
    pinned?: boolean;
}

/**
 * Check if a given object implements the InstallPackageParams interface.
 */
export function instanceOfInstallPackageParams(value: object): value is InstallPackageParams {
    if (!('manager' in value) || value['manager'] === undefined) return false;
    if (!('_package' in value) || value['_package'] === undefined) return false;
    return true;
}

export function InstallPackageParamsFromJSON(json: any): InstallPackageParams {
    return InstallPackageParamsFromJSONTyped(json, false);
}

export function InstallPackageParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): InstallPackageParams {
    if (json == null) {
        return json;
    }
    return {
        
        'manager': json['manager'],
        '_package': json['package'],
        'version': json['version'] == null ? undefined : json['version'],
        'hash': json['hash'] == null ? undefined : json['hash'],
        'pinned': json['pinned'] == null ? undefined : json['pinned'],
    };
}

export function InstallPackageParamsToJSON(value?: InstallPackageParams | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'manager': value['manager'],
        'package': value['_package'],
        'version': value['version'],
        'hash': value['hash'],
        'pinned': value['pinned'],
    };
}

