/* tslint:disable */
/* eslint-disable */
/**
 * agentctl API
 * Schema-first contract for `agentctl`.  The Go CLI is the current implementation, but this API document is the canonical cross-language contract for generated JS and Python clients. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelRequestContext
 */
export interface ModelRequestContext {
    /**
     * 
     * @type {string}
     * @memberof ModelRequestContext
     */
    sessionId: string;
    /**
     * 
     * @type {string}
     * @memberof ModelRequestContext
     */
    model?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelRequestContext
     */
    agent?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelRequestContext
     */
    turn?: number;
    /**
     * 
     * @type {Date}
     * @memberof ModelRequestContext
     */
    timestamp: Date;
}

/**
 * Check if a given object implements the ModelRequestContext interface.
 */
export function instanceOfModelRequestContext(value: object): value is ModelRequestContext {
    if (!('sessionId' in value) || value['sessionId'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function ModelRequestContextFromJSON(json: any): ModelRequestContext {
    return ModelRequestContextFromJSONTyped(json, false);
}

export function ModelRequestContextFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelRequestContext {
    if (json == null) {
        return json;
    }
    return {
        
        'sessionId': json['session_id'],
        'model': json['model'] == null ? undefined : json['model'],
        'agent': json['agent'] == null ? undefined : json['agent'],
        'turn': json['turn'] == null ? undefined : json['turn'],
        'timestamp': (new Date(json['timestamp'])),
    };
}

export function ModelRequestContextToJSON(value?: ModelRequestContext | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'session_id': value['sessionId'],
        'model': value['model'],
        'agent': value['agent'],
        'turn': value['turn'],
        'timestamp': ((value['timestamp']).toISOString()),
    };
}

