/* tslint:disable */
/* eslint-disable */
/**
 * agentctl API
 * Schema-first contract for `agentctl`.  The Go CLI is the current implementation, but this API document is the canonical cross-language contract for generated JS and Python clients. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReplayRequest
 */
export interface ReplayRequest {
    /**
     * 
     * @type {string}
     * @memberof ReplayRequest
     */
    sessionId: string;
    /**
     * 
     * @type {string}
     * @memberof ReplayRequest
     */
    policyPath?: string;
    /**
     * 
     * @type {number}
     * @memberof ReplayRequest
     */
    limit?: number;
}

/**
 * Check if a given object implements the ReplayRequest interface.
 */
export function instanceOfReplayRequest(value: object): value is ReplayRequest {
    if (!('sessionId' in value) || value['sessionId'] === undefined) return false;
    return true;
}

export function ReplayRequestFromJSON(json: any): ReplayRequest {
    return ReplayRequestFromJSONTyped(json, false);
}

export function ReplayRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReplayRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'sessionId': json['session_id'],
        'policyPath': json['policy_path'] == null ? undefined : json['policy_path'],
        'limit': json['limit'] == null ? undefined : json['limit'],
    };
}

export function ReplayRequestToJSON(value?: ReplayRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'session_id': value['sessionId'],
        'policy_path': value['policyPath'],
        'limit': value['limit'],
    };
}

