/* tslint:disable */
/* eslint-disable */
/**
 * agentctl API
 * Schema-first contract for `agentctl`.  The Go CLI is the current implementation, but this API document is the canonical cross-language contract for generated JS and Python clients. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Decision } from './Decision';
import {
    DecisionFromJSON,
    DecisionFromJSONTyped,
    DecisionToJSON,
} from './Decision';

/**
 * 
 * @export
 * @interface ReplayResponse
 */
export interface ReplayResponse {
    /**
     * 
     * @type {string}
     * @memberof ReplayResponse
     */
    sessionId: string;
    /**
     * 
     * @type {string}
     * @memberof ReplayResponse
     */
    policy: string;
    /**
     * 
     * @type {Array<Decision>}
     * @memberof ReplayResponse
     */
    results: Array<Decision>;
}

/**
 * Check if a given object implements the ReplayResponse interface.
 */
export function instanceOfReplayResponse(value: object): value is ReplayResponse {
    if (!('sessionId' in value) || value['sessionId'] === undefined) return false;
    if (!('policy' in value) || value['policy'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function ReplayResponseFromJSON(json: any): ReplayResponse {
    return ReplayResponseFromJSONTyped(json, false);
}

export function ReplayResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReplayResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'sessionId': json['session_id'],
        'policy': json['policy'],
        'results': ((json['results'] as Array<any>).map(DecisionFromJSON)),
    };
}

export function ReplayResponseToJSON(value?: ReplayResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'session_id': value['sessionId'],
        'policy': value['policy'],
        'results': ((value['results'] as Array<any>).map(DecisionToJSON)),
    };
}

