/* tslint:disable */
/* eslint-disable */
/**
 * agentctl API
 * Schema-first contract for `agentctl`.  The Go CLI is the current implementation, but this API document is the canonical cross-language contract for generated JS and Python clients. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RunCodeParams
 */
export interface RunCodeParams {
    /**
     * 
     * @type {string}
     * @memberof RunCodeParams
     */
    language: string;
    /**
     * 
     * @type {string}
     * @memberof RunCodeParams
     */
    command: string;
    /**
     * 
     * @type {string}
     * @memberof RunCodeParams
     */
    stdin?: string;
    /**
     * 
     * @type {boolean}
     * @memberof RunCodeParams
     */
    network?: boolean;
}

/**
 * Check if a given object implements the RunCodeParams interface.
 */
export function instanceOfRunCodeParams(value: object): value is RunCodeParams {
    if (!('language' in value) || value['language'] === undefined) return false;
    if (!('command' in value) || value['command'] === undefined) return false;
    return true;
}

export function RunCodeParamsFromJSON(json: any): RunCodeParams {
    return RunCodeParamsFromJSONTyped(json, false);
}

export function RunCodeParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): RunCodeParams {
    if (json == null) {
        return json;
    }
    return {
        
        'language': json['language'],
        'command': json['command'],
        'stdin': json['stdin'] == null ? undefined : json['stdin'],
        'network': json['network'] == null ? undefined : json['network'],
    };
}

export function RunCodeParamsToJSON(value?: RunCodeParams | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'language': value['language'],
        'command': value['command'],
        'stdin': value['stdin'],
        'network': value['network'],
    };
}

