/* tslint:disable */
/* eslint-disable */
/**
 * agentctl API
 * Schema-first contract for `agentctl`.  The Go CLI is the current implementation, but this API document is the canonical cross-language contract for generated JS and Python clients. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Decision } from './Decision';
import {
    DecisionFromJSON,
    DecisionFromJSONTyped,
    DecisionToJSON,
} from './Decision';

/**
 * 
 * @export
 * @interface TraceListResponse
 */
export interface TraceListResponse {
    /**
     * 
     * @type {Array<Decision>}
     * @memberof TraceListResponse
     */
    traces: Array<Decision>;
}

/**
 * Check if a given object implements the TraceListResponse interface.
 */
export function instanceOfTraceListResponse(value: object): value is TraceListResponse {
    if (!('traces' in value) || value['traces'] === undefined) return false;
    return true;
}

export function TraceListResponseFromJSON(json: any): TraceListResponse {
    return TraceListResponseFromJSONTyped(json, false);
}

export function TraceListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TraceListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'traces': ((json['traces'] as Array<any>).map(DecisionFromJSON)),
    };
}

export function TraceListResponseToJSON(value?: TraceListResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'traces': ((value['traces'] as Array<any>).map(DecisionToJSON)),
    };
}

