/* tslint:disable */
/* eslint-disable */
/**
 * agentctl API
 * Schema-first contract for `agentctl`.  The Go CLI is the current implementation, but this API document is the canonical cross-language contract for generated JS and Python clients. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WriteFileParams
 */
export interface WriteFileParams {
    /**
     * 
     * @type {string}
     * @memberof WriteFileParams
     */
    path: string;
    /**
     * 
     * @type {string}
     * @memberof WriteFileParams
     */
    operation: string;
    /**
     * 
     * @type {number}
     * @memberof WriteFileParams
     */
    sizeBytes?: number;
}

/**
 * Check if a given object implements the WriteFileParams interface.
 */
export function instanceOfWriteFileParams(value: object): value is WriteFileParams {
    if (!('path' in value) || value['path'] === undefined) return false;
    if (!('operation' in value) || value['operation'] === undefined) return false;
    return true;
}

export function WriteFileParamsFromJSON(json: any): WriteFileParams {
    return WriteFileParamsFromJSONTyped(json, false);
}

export function WriteFileParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): WriteFileParams {
    if (json == null) {
        return json;
    }
    return {
        
        'path': json['path'],
        'operation': json['operation'],
        'sizeBytes': json['size_bytes'] == null ? undefined : json['size_bytes'],
    };
}

export function WriteFileParamsToJSON(value?: WriteFileParams | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'path': value['path'],
        'operation': value['operation'],
        'size_bytes': value['sizeBytes'],
    };
}

